# Tell Travis you want a Python environment to test in
language: python

# List the versions of Python you'd like to test against
python:
  - "3.4"

# List the versions of Django you'd like to test against
env:
  - DJANGO_VERSION=1.9.1 DB=postgres

# Add Our Database
addons:
  postgresql: "9.4"

services:
  - postgresql

# Tell it the things it will need to install when it boots
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q -r requirements.txt

before_script:
  - cp config/database.yml.travis config/database.yml

# command to run tests
script: python manage.py test