# Tell Travis you want a Python environment to test in
language: python

# List the versions of Python you'd like to test against
python:
  - "3.4"

# Add Our Database
addons:
  postgresql: "9.4"

services:
  - postgresql

# Tell it the things it will need to install when it boots
install:
  - pip install Django==1.9.1
  - pip install psycopg2==2.6.1
  - pip install gunicorn==19.4.5
  - pip install Pillow==3.1.0
  - pip install djangorestframework==3.3.2
  - pip install markdown==2.6.5
  - pip install django-filter==0.12.0
  - pip install python-social-auth==0.2.14
  - pip install django-cors-headers==1.1.0
  - pip install django-modeltranslation==0.11rc2
  - pip install django_compressor==2.0

before_script:
  - psql <<EOF
  - \x
  - create database fly_db;
  - \c fly_db
  - GRANT ALL PRIVILEGES ON DATABASE fly_db to django;
  - ALTER USER django CREATEDB;
  - EOF
  - cp src/fly_project/fly_project/secret_settings_example.py src/fly_project/fly_project/secret_settings.py
  - cd src/fly_project

script: python manage.py test